image: Ubuntu

stack: jdk 11

branches:
only:
- master

build: off

install:
- java -jar artifacts/app-ibank.jar -P:profile=test &
- chmod +x gradlew

build script:
- ./gradlew test --info -Dselenide.headkess=true
